declare const _exports: {
    FixedNumber: typeof import("./fixednumber").FixedNumber;
    formatUnits(value: import("./units").BigNumberish, decimals?: number | undefined): string;
    parseUnits(value: string, decimals?: number | undefined): bigint;
    formatEther(value: import("./units").BigNumberish): string;
    parseEther(value: string): bigint;
    WeiPerEther: bigint;
    checkResultErrors(result: any): Array<{
        error: Error;
        path: Array<string | number>;
    }>;
    Result: typeof import("./result").Result;
    encodeRlp(value: any): string;
    decodeRlp(data: string): any;
    keccak256(data: string | Uint8Array): string;
    sha256(data: string | Uint8Array): string;
    sha512(data: string | Uint8Array): string;
    ripemd160(data: string | Uint8Array): string;
    id(text: string): string;
    hashMessage(message: string | Uint8Array): string;
    randomBytes(length: number): Uint8Array;
    computeHmac(algorithm: string, key: string | Uint8Array, data: string | Uint8Array): string;
    pbkdf2(password: string | Uint8Array, salt: string | Uint8Array, iterations: number, keylen: number, algorithm?: string | undefined): string;
    scrypt(password: string | Uint8Array, salt: string | Uint8Array, N: number, r: number, p: number, dkLen: number): Promise<string>;
    scryptSync(password: string | Uint8Array, salt: string | Uint8Array, N: number, r: number, p: number, dkLen: number): string;
    toUtf8String(data: import("./encoding").BytesLike): string;
    toUtf8Bytes(str: string): Uint8Array;
    toHex(data: import("./encoding").BytesLike): string;
    hexlify(data: import("./encoding").BytesLike): string;
    arrayify(data: import("./encoding").BytesLike): Uint8Array;
    concat(items: import("./encoding").BytesLike[]): string;
    stripZerosLeft(data: import("./encoding").BytesLike): string;
    encodeBytes32String(text: string): string;
    decodeBytes32String(bytes: import("./encoding").BytesLike): string;
    decodeBase58(data: string): Uint8Array;
    decodeBase64(data: string): Uint8Array;
    encodeBase58(data: import("./encoding").BytesLike): string;
    encodeBase64(data: import("./encoding").BytesLike): string;
    toUtf8CodePoints(str: string): number[];
    isBytesLike(value: any): boolean;
    zeroPad(value: import("./encoding").BytesLike, length: number): string;
    zeroPadValue(value: import("./encoding").BytesLike, length: number): string;
    solidityPacked(): void;
    solidityPackedKeccak256(): void;
    solidityPackedSha256(): void;
    isHexString: typeof import("./encoding").isHexString;
    bytesToHex: typeof import("./encoding").bytesToHex;
    hexToBytes: typeof import("./encoding").hexToBytes;
    isAddress(address: string): boolean;
    getAddress(address: string): string;
    isAddressable(value: any): boolean;
    resolveAddress(target: any): string | Promise<string>;
    getContractAddress(tx: {
        from: string;
        nonce: number;
    }): string;
    getCreateAddress(tx: {
        from: string;
        nonce: number;
    }): string;
    getCreate2Address(from: string, salt: string, initCodeHash: string): string;
    computeAddress(key: string | Uint8Array): string;
};
export = _exports;
