declare const _exports: {
    isError(error: any, code: string): boolean;
    isCallException(error: any): boolean;
    makeError(message: string, code: errors.ErrorCode, info?: Record<string, any> | undefined): Error & {
        code: errors.ErrorCode;
        shortMessage: string;
    };
    assert(check: any, message: string, code: errors.ErrorCode, info?: Record<string, any> | undefined): void;
    assertArgument(check: any, message: string, name: string, value: any): void;
    assertSecretArgument(check: any, message: string, name: string): void;
    ProviderError: typeof errors.ProviderError;
    TransactionError: typeof errors.TransactionError;
    ContractError: typeof errors.ContractError;
    FixedNumber: typeof import("./utils/fixednumber").FixedNumber;
    formatUnits(value: import("./utils/units").BigNumberish, decimals?: number | undefined): string;
    parseUnits(value: string, decimals?: number | undefined): bigint;
    formatEther(value: import("./utils/units").BigNumberish): string;
    parseEther(value: string): bigint;
    WeiPerEther: bigint;
    checkResultErrors(result: any): Array<{
        error: Error;
        path: Array<string | number>;
    }>;
    Result: typeof import("./utils/result").Result;
    encodeRlp(value: any): string;
    decodeRlp(data: string): any;
    keccak256(data: string | Uint8Array): string;
    sha256(data: string | Uint8Array): string;
    sha512(data: string | Uint8Array): string;
    ripemd160(data: string | Uint8Array): string;
    id(text: string): string;
    hashMessage(message: string | Uint8Array): string;
    randomBytes(length: number): Uint8Array;
    computeHmac(algorithm: string, key: string | Uint8Array, data: string | Uint8Array): string;
    pbkdf2(password: string | Uint8Array, salt: string | Uint8Array, iterations: number, keylen: number, algorithm?: string | undefined): string;
    scrypt(password: string | Uint8Array, salt: string | Uint8Array, N: number, r: number, p: number, dkLen: number): Promise<string>;
    scryptSync(password: string | Uint8Array, salt: string | Uint8Array, N: number, r: number, p: number, dkLen: number): string;
    toUtf8String(data: import("./utils/encoding").BytesLike): string;
    toUtf8Bytes(str: string): Uint8Array;
    toHex(data: import("./utils/encoding").BytesLike): string;
    hexlify(data: import("./utils/encoding").BytesLike): string;
    arrayify(data: import("./utils/encoding").BytesLike): Uint8Array;
    concat(items: import("./utils/encoding").BytesLike[]): string;
    stripZerosLeft(data: import("./utils/encoding").BytesLike): string;
    encodeBytes32String(text: string): string;
    decodeBytes32String(bytes: import("./utils/encoding").BytesLike): string;
    decodeBase58(data: string): Uint8Array;
    decodeBase64(data: string): Uint8Array;
    encodeBase58(data: import("./utils/encoding").BytesLike): string;
    encodeBase64(data: import("./utils/encoding").BytesLike): string;
    toUtf8CodePoints(str: string): number[];
    isBytesLike(value: any): boolean;
    zeroPad(value: import("./utils/encoding").BytesLike, length: number): string;
    zeroPadValue(value: import("./utils/encoding").BytesLike, length: number): string;
    solidityPacked(): void;
    solidityPackedKeccak256(): void;
    solidityPackedSha256(): void;
    isHexString: typeof import("./internal/hex").isHexString;
    bytesToHex: typeof import("./internal/hex").bytesToHex;
    hexToBytes: typeof import("./internal/hex").hexToBytes;
    isAddress(address: string): boolean;
    getAddress(address: string): string;
    isAddressable(value: any): boolean;
    resolveAddress(target: any): string | Promise<string>;
    getContractAddress(tx: {
        from: string;
        nonce: number;
    }): string;
    getCreateAddress(tx: {
        from: string;
        nonce: number;
    }): string;
    getCreate2Address(from: string, salt: string, initCodeHash: string): string;
    computeAddress(key: string | Uint8Array): string;
    Interface: typeof import("./abi/interface").Interface;
    AbiCoder: typeof import("./abi/interface").AbiCoder;
    Fragment: typeof import("./abi/fragments").Fragment;
    NamedFragment: typeof import("./abi/fragments").NamedFragment;
    FunctionFragment: typeof import("./abi/fragments").FunctionFragment;
    EventFragment: typeof import("./abi/fragments").EventFragment;
    ErrorFragment: typeof import("./abi/fragments").ErrorFragment;
    ConstructorFragment: typeof import("./abi/fragments").ConstructorFragment;
    StructFragment: typeof import("./abi/fragments").StructFragment;
    FallbackFragment: typeof import("./abi/fragments").FallbackFragment;
    ContractFactory: typeof import("./contract/contract-factory").ContractFactory;
    _sanitizeOverrides(overrides: any): Record<string, any>;
    BaseContract: typeof import("./contract/contract").BaseContract;
    Contract: typeof import("./contract/contract").Contract;
    ContractTransactionResponse: typeof import("./contract/contract").ContractTransactionResponse;
    ContractTransactionReceipt: typeof import("./contract/contract").ContractTransactionReceipt;
    EventLog: typeof import("./contract/contract").EventLog;
    verifyMessage(message: string | Uint8Array, signature: string | Uint8Array): string;
    SigningKey: typeof import("./wallet/wallet").SigningKey;
    AbstractSigner: typeof import("./wallet/wallet").AbstractSigner;
    BaseWallet: typeof import("./wallet/wallet").BaseWallet;
    Wallet: typeof import("./wallet/wallet").Wallet;
    NonceManager: typeof import("./wallet/wallet").NonceManager;
    JsonRpcSigner: typeof import("./wallet/wallet").JsonRpcSigner;
    VoidSigner: typeof import("./wallet/wallet").VoidSigner;
    getProvider(endpoint?: string | undefined, chainId?: number | undefined): import("./providers/provider").AbstractProvider;
    WebSocketProvider: typeof import("./providers/extra-providers").WebSocketProvider;
    IpcSocketProvider: typeof import("./providers/extra-providers").IpcSocketProvider;
    BrowserProvider: typeof import("./providers/extra-providers").BrowserProvider;
    FallbackProvider: typeof import("./providers/extra-providers").FallbackProvider;
    FilterByBlockHash: typeof import("./providers/extra-providers").FilterByBlockHash;
    JsonRpcProvider: typeof import("./providers/json-rpc-provider").JsonRpcProvider;
    JsonRpcApiProvider: typeof import("./providers/json-rpc-provider").JsonRpcApiProvider;
    Provider: typeof import("./providers/provider").Provider;
    AbstractProvider: typeof import("./providers/provider").AbstractProvider;
    Block: typeof import("./providers/provider").Block;
    TransactionResponse: typeof import("./providers/provider").TransactionResponse;
    TransactionReceipt: typeof import("./providers/provider").TransactionReceipt;
    Log: typeof import("./providers/provider").Log;
    FeeData: typeof import("./providers/provider").FeeData;
    version: string;
    ZeroAddress: string;
    ZeroHash: string;
    MaxUint256: bigint;
    MaxUint160: bigint;
    MinInt256: bigint;
    MaxInt256: bigint;
    NumericFault: string;
    NumericFaultCode: string;
    EtherSymbol: string;
    N: bigint;
};
export = _exports;
import errors = require("./errors");
